### ISSUE TITLE
user_path requires link_to, otherwise displays the path.

### ISSUE THREAD

**Issue by jengel3** [mc-extras/SpongeDev#11]
Example: http://sponge.jake0oo0.me/plugins/1-Towerbuild%20to%20Babel

Culprit being:

```
= user_path(comment.user)
```

It would probably be best to keep a helper method:

```
def profile_path(user)
link_to user.username, user
end
```

Otherwise we have to add a link_to to each user path.

**Comment by ThunderGemios10** [comment]
Hmm, Uh there seems to be a bug. It displays /users/ThunderGemios10/ instead of "ThunderGemios10"

**Comment by jomo** [comment]
Hmm, what exactly is the issue here? Not sure if I understand.

There is a difference between a path (/foo/bar) and a link (<a href=...), right?

**Comment by jomo** [comment]
Oh, I think I get it now. Well, it's called `user_path` and not `user_link` because it gives you the path, not the link. ;)

If you really want a helper for that, you should call it `user_link`.
I'm not sure if it will work, but it could be that `link_to @user` will set the link name to the user's name when we add

``` ruby
def to_s
  username
end
```

to the `User` class

**Comment by ThunderGemios10** [comment]
@jomo Seems legit. You can open up a Pull Request for that.

**Comment by jomo** [comment]
Maybe tonight (CET, that is)
